hooks:
  # only called when $DP_TOKEN is setup in git provider
  # and git provider is set up to call the DevPanel git hook
  git_hooks:
    push:
      - branch: "master"
        # matches release on "master" branch only
        # run commands or scripts from cmd below... eg:
        # echo "Hello World"
        # date >> test.txt
        cmd: |-
          /bin/bash .devpanel/init.sh >> /tmp/build_prod.txt
      - branch: "develop"
        # matches release on "develop" branch only
        # run commands or scripts from cmd below... eg:
        # echo "Hello World"
        # date >> test.txt
        cmd: |-
          /bin/bash .devpanel/init.sh >> /tmp/build_dev.txt
      - tag: ".*"
        # matches any tags
        # run commands or scripts from here; eg:
        cmd: |-
          /bin/bash .devpanel/init.sh >> /tmp/build_tag.txt
